name: Cleanup

on:
  schedule:
    - cron: "0 9 * * 1" # Every Monday at 9:00 AM

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: pierreraffa/cancel-previous-runs-action@1.11
        with:
          github_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4.4.1

      - name: Cleanup
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v2
        id: cleanup
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 60
          ignore_branches: main,stage,develop
          allowed_prefixes: feat/,fix/,hotfix/,docs/,style/,refactor/,perf/,test/,chore/
          dry_run: true

      - name: Notify
        run: echo -e "✅ Cleanup Successful:\n${{steps.cleanup.outputs.deleted_branches}}"
